### ISSUE TITLE
Saving issues.

### ISSUE THREAD

**Issue by Czernobo** [rodit/SnapMod#113]
Seems like you can't save stories and snap when you open them anymore. You can save them from inside the message thread only.

**Comment by rodit** [comment]
> Seems like you can't save stories and snap when you open them anymore.

Yes you can.

From the readme
> If you have an issue please post a log from LSPosed (I have no interest in supporting other Xposed implementations, although SnapMod should work fine with them) and a description of the issue. It is extremely unhelpful to just say "something doesn't work" or "I can't download stories."

I test every easily testable feature before I release updates (I'm not quite sure how or why you would assume otherwise). It is impossible for anybody to help you without more information (Android version, logs, configured download paths for snaps/stories).

**Comment by Magna-Graecia** [comment]
For what it's worth, both ways of saving are still working on my end, so it's likely just a local issue. Definitely give rodit some logs and the information he requested, and he might be able to see what the problem is.
