### ISSUE TITLE
Snapchat for my device is still 11.78.0.39

### ISSUE THREAD

**Issue by JReverse** [rodit/SnapMod#123]
Making this tweak not usable atm im on oneplus 10 pro

**Comment by rodit** [comment]
The only thing I can suggest is you wait until it's available or just download the APK from APKMirror. Which tweak are you talking about anyway?

**Comment by JReverse** [comment]
I meant the snap mod my bad 🤣 use to ios wording ill try apk mirror

**Comment by rodit** [comment]
Hahaha no problem - it should work fine with the 11.78.1.39 apk on apk mirror.
