### ISSUE TITLE
[Suggestion]Auto Save Snaps

### ISSUE THREAD

**Issue by Singala929** [rodit/SnapMod#130]
Can you make all snaps automatically save in gallary?

**Comment by RevealedSoulEven** [comment]
I think someone already made a discussion tab for it. Also don't start a issue regarding features. Issue is for if you're facing any issue in the already given features.

If you want to suggest an idea then please head to the discussion tab.

**Comment by Singala929** [comment]
ok i will close issue.

**Comment by RevealedSoulEven** [comment]
Anyways rodi is already working on it. You'll get to see this soon

**Comment by Singala929** [comment]
nice, thank you for information.
