### ISSUE TITLE
Some sort of saving issue. 

### ISSUE THREAD

**Issue by Czernobo** [rodit/SnapMod#131]
Sorry to bother you again I guess. But almost nothing saves, until I remove the "%u_snap_%d" from the download path to all paths, for instance the default path is "$Movies/SnapMod/%u_snap_%d" to "$Movies/SnapMod/". The audio notes, story and snap. It won't save unless I I remove that part. I tried it on 3 different custom roms and on MIUI. And, when it saves now, it saves with the caption bar on the snap video. If anyone else knows how to "fix" this for me, feel free to help.

Edit. Fixed. Just had to change the %d to %t and now it all works. I'm keeping this here until you yourself close it because I don't know if it's a real issue or not.

**Comment by Czernobo** [comment]
To be clear, the only thing here is that when the path is "$Movies/SnapMod/%u_snap_%d" it doesn't save. But when I change it to "$Movies/SnapMod/%u_snap_%t" it saves normally without the captions on the snap, and with source quality.

**Comment by rodit** [comment]
That's quite odd - could you check your date format setting for me?

**Comment by rodit** [comment]
My best guess is whatever version/implementation of android doesn't like a character in the date format and won't allow it in paths/file names

**Comment by Czernobo** [comment]
"dd-MM-yyyy_HH:mm:ss" I leave it as the default one since it should be working as it should. But somehow weirdly doesn't.

**Comment by Czernobo** [comment]
It's especially weird because when I leave it as "%d" the only way I can save the received snaps, is by "save to camera roll" inside the message thread and the quality becomes like 50% less than it actually is. Plus, the caption bar on videos stays.

**Comment by rodit** [comment]
Yes - saving to camera roll uses Snapchat's built in saving mechanism (unless you have a custom snap path set, and the option to enable it toggled), otherwise the media is directly downloaded and saved (without edits) in original quality. Try changing the ':' to '-' in your date format.

**Comment by Czernobo** [comment]
Apparently the issue Android has is with the ':' sign. Because it works if it's '-'.

**Comment by Czernobo** [comment]
No problem. Thank you for the hard work, mate.
