### ISSUE TITLE
Snaps are not saving

### ISSUE THREAD

**Issue by Singala929** [rodit/SnapMod#136]
Snaps are not saving, when I press save nothing happened.

**Comment by Magna-Graecia** [comment]
Make sure you have storage permissions enabled in device settings. They don't get enabled automatically, and SnapMod doesn't ask permission for it. You need to manually go into device settings and enable it for SnapMod.. Also make sure that both "Save Any Message" and "Allow Saving Snaps" are enabled in SnapMod settings.

**Comment by rodit** [comment]
Please could you enable all log levels in snapmods settings and provide xposed logs after trying to save a snap - also what android version/Snapchat version you are using would be useful to know.

**Comment by AroPix** [comment]
I still have this problem, even tho i tried uninstalling and installing.
