### ISSUE TITLE
Sending >11s videos as live snaps/stories does not work from the Memories window

### ISSUE THREAD

**Issue by Magna-Graecia** [rodit/SnapMod#137]
To be clear, this only happens with >11s videos. Photos and videos <11s work fine. This also only happens when "Send Gallery as Snaps" is enabled. If this option is disabled, then they will send fine, but they get sent as chat videos (not live). This is normal of course. They also post to story with the option disabled, but not when it's enabled. This leads me to believe that it's tied to bypassing the video length restriction. The global "Bypass Video Length Restrictions" option must not be applying to the Memories window sort of like when it wasn't applying to videos shared from gallery to Snapchat even though it was applying when videos were longpressed from the in-chat gallery drawer to load them into the camera edit window. I could be entirely wrong though. You would know more than I do.

**Comment by RevealedSoulEven** [comment]
Yes, I was also talking about it. But anyways there is an alternative way to achieve that. So it's not an issue

**Comment by Magna-Graecia** [comment]
> Yes, I was also talking about it. But anyways there is an alternative way to achieve that. So it's not an issue

I know. Rodit told me to post a new issue for it here: https://github.com/rodit/SnapMod/issues/122

Also, posting from the Memories window is the only way to post a story with no "from camera roll" tag AND a custom timestamp using my method described here: https://github.com/rodit/SnapMod/discussions/105

This is why it's an issue. Otherwise I agree it wouldn't be one.

**Comment by rodit** [comment]
With Send Gallery as Snaps enabled, I have just tried this (with a 33s video) and it posts fine to my story (with and without 'Disable Snap Splitting' enabled). I can also long-press to edit and then post to my story/send as snap to anyone as normal.

**Comment by Magna-Graecia** [comment]
@rodit Yes, by 'memories window' we mean the one that appears when swiping up from the camera screen. There are 4 tabs in that window: Snaps, Stories, Camera Roll, and My Eyes Only. By long-pressing to edit, do you mean you long-pressed to get the checkmark on the video and the options that appear at the bottom, one of them being 'edit'? Then pressed 'edit' and sent from there? Did you send from the "Snaps" tab specifically?

I know for sure at least 3 people are experiencing this issue. Myself, RevealedSoulEven, and tarek133. Not sure if anyone else can confirm if they are as well.

**Comment by Magna-Graecia** [comment]
UPDATE: Are you sure the 33s video sent as the full video and not just the first 10 seconds of it?

I ask because this is what I just did after posting my previous reply: I went and recorded a 41 second video with my device camera through Snapchat, then hit the "save" button in the bottom left of the edit screen to save it to the "Snaps" section of Memories. I waited for it to be fully saved there (takes a few seconds), then I tried sending it to my other Snapchat account by long-pressing on it and tapping the send button. I got the uploading arrow in my status bar and also the "Sent" notification from Snapchat. This doesn't happen when the >11s videos don't send, so I thought "oh hey it's working, weird!"

So then I went on to do this: I found 2 old videos saved in my memories that are also saved on my device. The exact same videos. I tried to send those 2 videos saved in Memories and got nothing. They didn't send, and no notifications. I then went and shared those same 2 videos saved on my device from gallery to Snapchat, and then tapped the "Save" button in the bottom left to save them to Memories. I then proceeded to send those 2 videos to my other Snapchat, and it worked. I got the uploading arrow in status bar, and also the "Sent" notifications from Snapchat. So at this point I'm thinking "damn, it must just be an issue with trying to send old copies of videos saved in memories." I then went to my other Snapchat to watch the videos and noticed they were cut short. They were only the first 10 seconds, wtf? I then tried sending all videos one by one by long-pressing and tapping the edit button to put them into the edit window, then sending from there. Same thing. I also tried uploading them to my story. Same thing. They uploaded the first 10 seconds and that's it. When viewing all of them within Memories, they play the full video, so the full videos are definitely saved there. They're just only sending the first 10 seconds.

Can you verify that all 33s of your video was sent and not just the first 10 seconds?

**Comment by rodit** [comment]
The full video (all 33s) are visible from my story only when snap splitting is disabled in snapmod (otherwise I only get 10 seconds).

**Comment by Magna-Graecia** [comment]
@rodit Just tried it with snap splitting disabled and got the same result as you. Full videos now get sent and also upload to story, so that's a good thing. The only thing that sucks is we don't have the option to send with splits. Not that unsplit isn't clearly better or anything, but split is more realistic on Snapchat since everyone knows >10s videos get split. It's nice to have the option to choose for different scenarios. Do you think it's possible to get it to work with snap splitting enabled?

Just for the record. 2 of the videos I just sent that worked are exactly the same as the 2 old videos in Memories that don't work. I simply uploaded 2 new copies of those videos, and those new copies worked. The 2 old copies are from June 2021 and August 2020, so there must be some difference with how Snapchat saved videos at that time that's causing issues I'm guessing. So far from having tested, I've noticed that every newly uploaded video sends fine. It's only old videos that have the issue. Strange.

**Comment by rodit** [comment]
It's not as unrealistic as you think - the disabling of snap splitting is actually an AB tweak called 'ENABLE_LONG_SNAPS' which Snapmod just force enables (in addition to one other video length bypass). This suggests it will be a feature at some point in the future. It's actually quite difficult to pinpoint where splitting occurs outside this tweak, so I probably won't be able to get it to work as you say unfortunately.

**Comment by Magna-Graecia** [comment]
@rodit Oh really? Nice! I wasn't aware of that. That's good news then for the "realism" aspect of it haha. I mean unsplit is just flat out better, but ya if you're trying to make something look like it was a legitimately recorded live snap that's over 10 seconds long, then there needs to be splits (at least for the time being). But it looks like that will be changing, so fixing this is basically unnecessary anyway.

rodit hooking us up with the early access before all the plebs get to taste! 😂
