### ISSUE TITLE
Sent a message showing in in-app notifications while "Show messages in notification" is turned on

### ISSUE THREAD

**Issue by RevealedSoulEven** [rodit/SnapMod#139]
Yea it's one of the best features to see the new incoming messages in the notifications. And it's working well for system notifications. 

But when you're already in the snapchat application then the in-app notification still shows "sent a message" instead of displaying the message. I hope you will fix it very soon ❤️

![Screenshot_2022-05-18-09-14-49-161_com snapchat android](https://user-images.githubusercontent.com/49313374/168952934-89e8c665-2a14-4a01-8f69-a1b3da12a0eb.jpg)

Either replace that in-app notifications with system notification, but that's quite irritating. So better you can make some changes to the in-app notification instead.

Thank you! And as always, Many Many thanks for this great project

**Comment by Magna-Graecia** [comment]
You get a system notification while you're in the Snapchat app? What would be the point of that? Snapchat already gives you a notification in-app anyway by saying "New Chat" etc. No need for double notifications. I get them if I'm outside the app, or my screen is locked, but getting them while in Snapchat would be annoying, as it would block the upper part of the app for a few seconds, and if I'm already in the app then I can stealth view the chat right then and there with stealth mode or by using the "More Information" message preview.

I personally like it the way it is and wouldn't want it to change. I don't want notifications while I'm in-app. It's useless.

P.S. - How are you snap spamming the celebs? I used to do this too, and have a bunch of celebs added as friends from back then, but now they don't show up in the list of friends when sending snaps. Only people that have added me back show up. I thought this was a Snapchat change. Or maybe 2 months ago you were still able to and just have the "Delivered" still in your chats?

**Comment by RevealedSoulEven** [comment]
Still it's the same🥺
No changes

**Comment by rodit** [comment]
Hmm - I don't get the in app notifications for some reason so it's hard for me to test this. Is there an option for them?

**Comment by Magna-Graecia** [comment]
> Hmm - I don't get the in app notifications for some reason so it's hard for me to test this. Is there an option for them?

I don't get them either. I'm not sure you're even supposed to. It wouldn't make any sense because it's double notifications at that point since Snapchat already gives you them in-app. Overlay notifications while trying to use the app would just be a nuisance.

**Comment by RevealedSoulEven** [comment]
@rodit leave it anyways, the system notifications are okay btw. Also we can see chat previews in case of reading those messages. So it's useless instead.
