### ISSUE TITLE
Support to 32bit & SnapChat account Locked

### ISSUE THREAD

**Issue by cool125** [rodit/SnapMod#144]
Hey Sir,

1- Snapmod does not support android Lollipop/Marshmallow 32bit....  kindly add 32bit support

2- Snapchat is blocking account after 1 or two day after install the snapmod.
we all know that snapchat detect all type tweaks & hacks.
So kindly give us any solution to avoid account blocking.
i think u must add an One-Click Button option in snapmod to avoid SnapChat to detect any type of tweak or hack.

3- Can u make (without zygisk, min Nougat support) Magisk v23 SnapChat module to bypass SnapChat rooting (and all type of) detection which leads to cause the SnapChat locked/Blocked.

Waiting for the solutions.

Thanks.

**Comment by tarek133** [comment]
You are literally the first person to report that they've been blocked for using SnapMod. Are you sure you didn't do anything spam-related?

**Comment by cool125** [comment]
> You are literally the first person to report that they've been blocked for using SnapMod. Are you sure you didn't do anything spam-related?

no i did not spam.
i am using Oreo 8 android. 
Xposed
Rooted but safetynet NOT passed. 
using magisk v23 (no zygisk) using magisk hide option for SnapChat.

i made 4 or 5 snap chat accounts.  every account got TEMP LOCKED in 2 to 4 days.

**Comment by Pandasapling** [comment]
> 

Rodit said that there’s no support for other Xposed implementations. Normal Xposed will cause bans. I don’t believe that’s An issue with snapmod.

**Comment by jammyjay** [comment]
Some of these "requests/demands" are getting a bit ridiculous.

**Comment by Magna-Graecia** [comment]
> Some of these "requests/demands" are getting a bit ridiculous.

I 100% agree with this. A lot of these spam requests keep sounding more like demands in their tone, as if rodit actually owes us anything at all, but that's just me.

Anyway, for the record, I'm using Android 8.1.0 Oreo with original Xposed and Magisk v23, and I've never been banned. I also don't pass safetynet when Xposed is enabled, but I just disable it as it's systemless and then I pass it 100%. You only need to pass it to log into Snapchat. Once you're logged in, you can re-enable Xposed and restart your device and you're good to go.

Are you using Systemless Xposed? If not, then I guess that could be the issue. I'm not sure how you would log into Snapchat in the first place in that case unless you're using titanium backup to save your Snapchat data/token on a different device, then restoring it on your rooted device. That was the old school method, and this could potentially cause issues.

**Comment by Lucky-069** [comment]
> I'm using since almost 10 days now and still no issues with it.

Same here, also I have been using snapchat with magisk hide disabled yet no bans here. Snapchat doesn't checks root anymore! It won't block you for root I believe. It must be normal xposed. I have been using the mod since day one. No issues so far!

**Comment by cool125** [comment]
> > Some of these "requests/demands" are getting a bit ridiculous.
> 
> I 100% agree with this. A lot of these spam requests keep sounding more like demands in their tone, as if rodit actually owes us anything at all, but that's just me.
> 
> Anyway, for the record, I'm using Android 8.1.0 Oreo with original Xposed and Magisk v23, and I've never been banned. I also don't pass safetynet when Xposed is enabled, but I just disable it as it's systemless and then I pass it 100%. You only need to pass it to log into Snapchat. Once you're logged in, you can re-enable Xposed and restart your device and you're good to go.
> 
> Are you using Systemless Xposed? If not, then I guess that could be the issue. I'm not sure how you would log into Snapchat in the first place in that case unless you're using titanium backup to save your Snapchat data/token on a different device, then restoring it on your rooted device. That was the old school method, and this could potentially cause issues.



hi

i am using original xposed at 8.0.0 Oreo.
and i am directly being log into snapchat while original Xposed active.

**Comment by rodit** [comment]
If you are using normal (non-systemless) xposed, you may get banned by Snapchat. This is nothing to do with Snapmod. Snapmod should work fine with 32-bit android (although I do not plan on testing this or explicitly providing support as I do not have any 32 bit devices to test with, not to mention pretty much every device made in the last few years supports 64 bit android). Also, although the Snapmod APK supports Android 8, I only really care about supporting newer versions of Android. There is almost certainty that an actively used phone supports Android 9+ at the very least.

There is no code in Snapchat to detect Snapmod. No other users have been banned or 'detected' using it. It is therefore impossible for me to bypass this non-existent detection. I have addressed Snapmod being potentially banned/detected in the future in #16

**Comment by cool125** [comment]
> If you are using normal (non-systemless) xposed, you may get banned by Snapchat. This is nothing to do with Snapmod. Snapmod should work fine with 32-bit android (although I do not plan on testing this or explicitly providing support as I do not have any 32 bit devices to test with, not to mention pretty much every device made in the last few years supports 64 bit android). Also, although the Snapmod APK supports Android 8, I only really care about supporting newer versions of Android. There is almost certainty that an actively used phone supports Android 9+ at the very least.
> 
> There is no code in Snapchat to detect Snapmod. No other users have been banned or 'detected' using it. It is therefore impossible for me to bypass this non-existent detection. I have addressed Snapmod being potentially banned/detected in the future in #16


thanks for your reply Admin..

dear i tried to install snapmod app in lollipop 5 (32bit device) Marshmallow 6  (32bit device) , but i got the package error while installing the app.  kindly add support to 32bit devices android 5 & 6 if its not much problematic for you.  
i know its not much important but in old android (5,6) there r some xposed modules available which has ability to fully bypass root/xposed detection for any app. 
And it will be more safe to avoid banning snapchat on android 5/6 due to some old xposed modules that only fully support to old android 5/6 devices.



yes i am using normal xposed and i think its a reason for blocking my SnapChat account. 
So Now......
what i did..
i was using normal xposed so i uninstalled the firmware first then i remove xposed manager.  and restart the phone.
then i installed xposed manager for magisk.
and then i download systemless xposed firmware from magisk manger (105 mb zip file)
after flash and reboot the phone. xposed manager still showing it has not any xposed firmware installed.

help me if any Xposed's expert here.

**Comment by JReverse** [comment]
Regular xposed is detected see https://aeonlucid.com/Snapchat-detection-on-Android/ this is outdated but it shows some detect modules in the binary i have a more updated post ill post later.
