### ISSUE TITLE
Some options no longer appear

### ISSUE THREAD

**Issue by N0on32** [rodit/SnapMod#147]
After updating to 11.79, the look of  menu changed and some options no longer appear 
Previously, when I long press on the username, the menu appears like this

![Screenshot_٢٠٢٢٠٥٢٠-١٠٣٩٣٤_Snapchat](https://user-images.githubusercontent.com/105910941/169484502-ee85d07e-1c12-46f8-b690-fbe7acc5075e.jpg)

**Comment by N0on32** [comment]
And after the update
![Screenshot_٢٠٢٢٠٥٢٠-١٠٤١٠٨_Snapchat](https://user-images.githubusercontent.com/105910941/169485304-7b8ef03f-5c28-4b6f-b6cb-82a06a9d2722.jpg)

**Comment by RevealedSoulEven** [comment]
Uffff! That's snapchat update. It used to show like this in iOS before. And now it's coming like this in android too.

**Comment by rodit** [comment]
Is this when you long press on the chat feed or from toggling options on a friendship profile?

**Comment by N0on32** [comment]
When I long press on the chat feed

**Comment by rodit** [comment]
Okay, thanks - I'll have a look at it.

**Comment by N0on32** [comment]
Problem solved, thank you very much  😘🤗

**Comment by N0on32** [comment]
But voice and video calls no longer work

**Comment by rodit** [comment]
I haven't updated anything yet?

**Comment by N0on32** [comment]
I mean, I added this to the block list in the host file

https://aws.api.snapchat.com

The menu has returned to the old format

**Comment by N0on32** [comment]
I mean, I added this to the block list in the host file

aws.api.snapchat.com

The menu has returned to the old format

**Comment by N0on32** [comment]
I mean, I added this to the block list in the host file

aws.api.snapchat.com

The menu has returned to the old format

**Comment by rodit** [comment]
I added support for the new chat menu in 1.7.3 so you can choose between the new and old chat menu without blocking `aws.api.snapchat.com`
