### ISSUE TITLE
Username in saved file?

### ISSUE THREAD

**Issue by degsyh** [rodit/SnapMod#15]
Hello, great mod. Keep up the good work!

Question - is it possible to add the user id of the person when saving the snap or video into the filename? There was a previous app where saved snaps were saved in a specific folder as per the username of the snapee.

**Comment by rodit** [comment]
This is something I am working on - at the moment, friends' stories will have their username in the file name but for public profiles etc, the username isn't readily available from the story info, although I'm sure it's obtainable elsewhere.

**Comment by rodit** [comment]
This is fixed in 1.4.1

**Comment by degsyh** [comment]
Thanks for this. Stories vids and snaps from stories works perfectly. Any chance the same can be done for normal snaps that are sent in chat?

**Comment by rodit** [comment]
Fixed in 1.5.7
