### ISSUE TITLE
Saving issues / nougat

### ISSUE THREAD

**Issue by beakwood** [rodit/SnapMod#157]
Im having some saving issues on nougat. All tweaks works fine just issues with download doesnt download to "movies/snapmod/%u_story_%d" i also untoggled android 11 file system and changed the %d to %t. Also as last resort, i uninstalled and reinstalled snapchat 11.79.0.34 /snapmod. Neither if the methods worked. I see the "saving started" toast but doesnt download

Heres the module logs 
https://pastebin.com/N3Uux20V

**Comment by Alix8804** [comment]
> Im having some saving issues on nougat. All tweaks works fine just issues with download doesnt download to "movies/snapmod/%u_story_%d" i also untoggled android 11 file system and changed the %d to %t. Also as last resort, i uninstalled and reinstalled snapchat 11.79.0.34 /snapmod. Neither if the methods worked. I see the "saving started" toast but doesnt download
> 
> Heres the module logs https://pastebin.com/N3Uux20V

Same to me only unopen streak with long press saved in DCIM Snapchat without sender name story and snap from save button not working please fix this

**Comment by Radzi11** [comment]
i have the same the only way to save is a combination key.

**Comment by Alix8804** [comment]
> Make sure storage permissions are granted in device settings for SnapMod. They weren't granted by default for me, and I didn't get asked permission, so I thought something was wrong with saving at first. After I went into device settings and granted it manually, everything worked fine. A few people had posted before thinking something was wrong when this was actually the issue, so just informing in case this is also the issue for you both.

I granted permission still not working please tell us what version of android you are using 10 11 or 12 please

**Comment by Radzi11** [comment]
the problem is apparently in the release not on the phone because I have the same on 2 devices

**Comment by Radzi11** [comment]
> Try and change the “:” in change date format to “-“
Yea it helped thx

**Comment by rodit** [comment]
Yes this is a known issue. By default, the date format used to contain ':' which seems to not be allowed in file names on some versions of Android. The default now uses '-' instead of ':' which is why reinstalling SnapMod will fix the issue for most people. @beakwood can you try this and see if you can save after replacing ':' with '-' in the date format setting.

**Comment by beakwood** [comment]
> Yes this is a known issue. By default, the date format used to contain ':' which seems to not be allowed in file names on some versions of Android. The default now uses '-' instead of ':' which is why reinstalling SnapMod will fix the issue for most people. @beakwood can you try this and see if you can save after replacing ':' with '-' in the date format setting.

Yes I've tried this, as this was among one of the first methods. I just enabled storage permissions and it still only shows the toast of 'start downloading' but not downloading. Every other tweak seems to be working just not the saving. Currently have Date Format as dd-MM-yyyy_HH-mm-ss and tried both enable / disable Use Android Download Manager. Also just updated my magisk just because and the issue persists.

**Comment by rodit** [comment]
What is the story download path configured to? Is it the default (`$Movies/SnapMod/...`)?

**Comment by beakwood** [comment]
It's currently at ($Movies/SnapMod/%u_story_%d )

**Comment by rodit** [comment]
It would be very useful if you could get some logcat output for me. You can run `adb shell "logcat | grep Download"` from your computer with your device connected and post the output here.

**Comment by rodit** [comment]
Yes, change your date format by replacing the ':' with '-': change it from `dd-MM-yyyy_HH:mm:ss` to `dd-MM-yyyy_HH-mm-ss`

**Comment by Alix8804** [comment]
> 

Changing date from 
dd-MM-yyyy_HH:mm:ss to dd-MM-yyyy_HH-mm-ss 
Every thing work fine
ROM crdroid android 11

**Comment by beakwood** [comment]
logcat using adb
`05-25 14:51:30.684 32630 32727 I Finsky  : [2896] ipv.g(1): getDownloads()
05-25 14:51:31.026 32741   300 I Finsky:background: [2859] inh.f(1): getDownloads()
05-25 14:51:31.030 32630 32657 I Finsky  : [2856] ipv.g(1): getDownloads()
05-25 14:51:31.031 32741   300 I Finsky:background: [2859] inh.f(1): getDownloads()
05-25 14:51:41.092 32630   397 I Finsky  : [2920] ipv.g(1): getDownloads()
05-25 14:51:41.104 32630   397 I Finsky  : [2920] qw.run(14): Initialized AssetModuleDownloader.
05-25 14:51:41.113 32741   300 I Finsky:background: [2859] inh.f(1): getDownloads()
05-25 14:55:26.433  7063 19032 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Movies/SnapMod/sickathanuravrg_story_1653515726361.mp4
05-25 14:55:26.511  7063   855 D DownloadManager: [37] Starting xyz.rodit.snapmod
05-25 14:55:26.519  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 14:55:27.271  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 14:55:27.292  7063   855 D DownloadManager: [37] Finished with status SUCCESS
05-25 14:55:27.293  7063   855 V DownloadManager: MIME Type = null
05-25 14:55:27.311  7063   855 D DownloadManager: Send intent: mId:37 status:200 mTitle:sickathanuravrg's Story
05-25 14:55:27.314  7063  7201 I DownloadManager: Notification Clear Download 1:xyz.rodit.snapmod
05-25 14:55:27.585  7063   855 I DownloadManager: Download 37 finished with status SUCCESS
05-25 14:56:10.041  7063 11926 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Movies/SnapMod/sickathanuravrg_story_1653515770011.mp4
05-25 14:56:10.101  7063  1119 D DownloadManager: [38] Starting xyz.rodit.snapmod
05-25 14:56:10.126  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 14:56:10.257  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 14:56:10.290  7063  1119 D DownloadManager: [38] Finished with status SUCCESS
05-25 14:56:10.290  7063  1119 V DownloadManager: MIME Type = null
05-25 14:56:10.295  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 14:56:10.300  7063  1119 D DownloadManager: Send intent: mId:38 status:200 mTitle:sickathanuravrg's Story
05-25 14:56:10.313  7063  7201 I DownloadManager: Notification Clear Download 1:xyz.rodit.snapmod
05-25 14:56:10.384  7063  1119 I DownloadManager: Download 38 finished with status SUCCESS
05-25 15:09:18.611  7063 18912 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Movies/SnapMod/sickathanuravrg_story_1653516558579.mp4
05-25 15:09:18.670  7063  1737 D DownloadManager: [39] Starting xyz.rodit.snapmod
05-25 15:09:18.688  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 15:09:19.213  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 15:09:19.241  7063  1737 D DownloadManager: [39] Finished with status SUCCESS
05-25 15:09:19.242  7063  1737 V DownloadManager: MIME Type = null
05-25 15:09:19.253  7063  1737 D DownloadManager: Send intent: mId:39 status:200 mTitle:sickathanuravrg's Story
05-25 15:09:19.254  7063  7201 I DownloadManager: Notification Clear Download 1:xyz.rodit.snapmod
05-25 15:09:19.416  7063  1737 I DownloadManager: Download 39 finished with status SUCCESS
05-25 15:10:22.128  7063  8934 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Movies/SnapMod/sickathanuravrg_story_1653516622100.mp4
05-25 15:10:22.185  7063  1803 D DownloadManager: [40] Starting xyz.rodit.snapmod
05-25 15:10:22.198  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 15:10:22.272  7063  7201 D DownloadManager: Notification equeued Download : 1:xyz.rodit.snapmod
05-25 15:10:22.286  7063  1803 D DownloadManager: [40] Finished with status SUCCESS
05-25 15:10:22.287  7063  1803 V DownloadManager: MIME Type = null
05-25 15:10:22.297  7063  1803 D DownloadManager: Send intent: mId:40 status:200 mTitle:sickathanuravrg's Story
05-25 15:10:22.300  7063  7201 I DownloadMana`

**Comment by beakwood** [comment]
I'm not entirely sure if clearing the cache/data of "My Files" app is what made it work. Since I checked the error from the logcat "Path appears to be invalid: /storage/emulated/0/Movies/SnapMod/" and was looking for DownloadManager app to clear cache/data but couldn't find it in my Apps settings. Also I'm running Android Pie. I forgot I was no longer using nougat and came across this link which references Android Pie 9.0 https://redmine.stoutner.com/issues/332 
But, it's working as intended.

**Comment by rodit** [comment]
Great, I'm glad you found a fix.
