### ISSUE TITLE
Feature request:dark mode

### ISSUE THREAD

**Issue by WmeLuna** [rodit/SnapMod#158]
i use swift installer to get a dark mode on snap but its a bit buggy and specifically snapchat is laggy with swift
an alternative for dark mode would match well with this module

**Comment by iRashiD-AE** [comment]
#111

**Comment by iRashiD-AE** [comment]
> i use swift installer to get a dark mode on snap but its a bit buggy and specifically snapchat is laggy with swift an alternative for dark mode would match well with this module

#111

**Comment by drickles** [comment]
Yh I heard snapchat has native dark mode that should automatically turn on with the device's light or dark mode settings but for the life of me I've never been able to get it to work. If a force trigger is possible that would be great

**Comment by rodit** [comment]
I have already discussed this in previous issues/feature requests. I will not be implementing dark mode anytime soon unless I stumble across an easy way to do it.

**Comment by romhacks** [comment]
> i use swift installer to get a dark mode on snap but its a bit buggy and specifically snapchat is laggy with swift
> an alternative for dark mode would match well with this module

I find that using the Swift Black theme, but with substratum lite as the overlay manager instead of Swift installer, it is quite stable and snappy.

**Comment by tycoon420** [comment]
![Screenshot_20220603-160453_Snapchat](https://user-images.githubusercontent.com/11652113/171839582-4e65f6de-f3d6-4204-aa74-601320a356ec.jpg)
If you are using samsung device, you can use hex theme. No lag of anything with hex overlay.

**Comment by tycoon420** [comment]
![Screenshot_20220603-161728_Snapchat](https://user-images.githubusercontent.com/11652113/171839875-108c2819-3fe3-4834-ac9d-165c04cb119c.jpg)
Full dark black theme. It looks dope.😍
