### ISSUE TITLE
snapmod showing error after I updated Snapchat to latest version on playstore

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [rodit/SnapMod#161]
I'm currently using 1.7.3 version of snapmod and just recently updated to Snapchat version 11.80.0.32. previous version it was working well but then at this latest version it shows like this in below screenshot. Please do help me.
![Screenshot_20220525-074105_SnapMod](https://user-images.githubusercontent.com/78001660/170165110-eab2a3b0-ca25-43dd-a274-cd716cb7a498.png)
#

**Comment by jammyjay** [comment]
It literally says it right there in bold red letters. "Unsupported".

The github page says "**The latest and only fully supported version of Snapchat is 11.79.0.34**". Sometimes we need to read before running complaining that the sky is falling and creating a issue where none exists.

Downgrade your snapchat. Simple.

**Comment by romhacks** [comment]
This happens every version because the developer can't update the mappings instantly. You can either downgrade the app, deal with the lack of mods until the mod is updated, or not update the app until the mod is updated.

**Comment by Midnightmadwalk-coder** [comment]
> 

In the GitHub page it also says  11.79.0.34 and **onwards**.

**Comment by Midnightmadwalk-coder** [comment]
> This happens every version because the developer can't update the mappings instantly. You can either downgrade the app, deal with the lack of mods until the mod is updated, or not update the app until the mod is updated.

Is there anything I can do to update the mappings manually through a root file manager app?

**Comment by iRashiD-AE** [comment]
> > This happens every version because the developer can't update the mappings instantly. You can either downgrade the app, deal with the lack of mods until the mod is updated, or not update the app until the mod is updated.
> 
> Is there anything I can do to update the mappings manually through a root file manager app?

Yes , rename build to 84611 , But I don't think it will work

**Comment by rodit** [comment]
The only way to update the mappings for an unsupported version is to run dexsearch yourself on the new APK and copy the generated mappings file over with the correct name. I would suggest you turn Snapchat auto updates off and wait a couple of days after each release until I add support for the latest version. I will likely add support today.

**Comment by Midnightmadwalk-coder** [comment]
> The only way to update the mappings for an unsupported version is to run dexsearch yourself on the new APK and copy the generated mappings file over with the correct name. I would suggest you turn Snapchat auto updates off and wait a couple of days after each release until I add support for the latest version. I will likely add support today.

Tysm

**Comment by Midnightmadwalk-coder** [comment]
> > > This happens every version because the developer can't update the mappings instantly. You can either downgrade the app, deal with the lack of mods until the mod is updated, or not update the app until the mod is updated.
> > 
> > 
> > Is there anything I can do to update the mappings manually through a root file manager app?
> 
> Yes , rename build to 84611 , But I don't think it will work

U can tell the steps? I'll try & check
