### ISSUE TITLE
Disable Snap Splitting doesn't work anymore

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#162]
Enabling the option that disables snap splitting, won't do what it's supposed to anymore. Snaps still get splitted and you have to tap on the snap after 10 seconds to get to the next part.
It worked a few days ago but weirdly enough, it stopped working now. Using latest SnapMod with latest supported Snapchat

**Comment by Magna-Graecia** [comment]
What do you mean you need to tap to get to the next part? It doesn't work on received video snaps. It's for sending video snaps as one long video instead of being split into multiple 10s snaps.

**Comment by rodit** [comment]
Yes, as @Magna-Graecia says, snap splitting is for outgoing snaps. If you would like to rejoin split snaps sent to you, you will have to download the parts and use another app to join them.

**Comment by tarek133** [comment]
@rodit I mean it like that: When you send a video longer than 10 seconds with disable snap splitting enabled, it does show as one video to the recipient. But it's still possible to click through the snap, as it was a splitted snap. 
Please watch the video gor reference:
https://streamable.com/q2ydju

**Comment by Magna-Graecia** [comment]
> @rodit I mean it like that: When you send a video longer than 10 seconds with disable snap splitting enabled, it does show as one video to the recipient. But it's still possible to click through the snap, as it was a splitted snap. Please watch the video for reference: https://streamable.com/q2ydju

This is normal. You have the benefit of having uninterrupted video and audio while still being able to fast-forward the snap by tapping, so it's better this way. Rodit has stated that 'long snaps' is an upcoming feature by Snapchat that he has just basically unlocked for us ahead of time, so however it works now is I'm sure how Snapchat designed it to work, and the way it will work when it becomes an official feature for everyone. What would you rather have alternatively? Forcing people to have to watch every second with no option to fast forward a bit? This is counterproductive and counterintuitive. The way it currently works is the better way. You're still reaping the intended benefit either way, which is audio and video with no interruptions. It's not intended to force people to watch every second without the option to skip lol

**Comment by tarek133** [comment]
> > @rodit I mean it like that: When you send a video longer than 10 seconds with disable snap splitting enabled, it does show as one video to the recipient. But it's still possible to click through the snap, as it was a splitted snap. Please watch the video for reference: https://streamable.com/q2ydju
> 
> This is normal. You have the benefit of having uninterrupted video and audio while still being able to fast-forward the snap by tapping, so it's better this way. Rodit has stated that 'long snaps' is an upcoming feature by Snapchat that he has just basically unlocked for us ahead of time, so however it works now is I'm sure how Snapchat designed it to work, and the way it will work when it becomes an official feature for everyone. What would you rather have alternatively? Forcing people to have to watch every second with no option to fast forward a bit? This is counterproductive and counterintuitive. The way it currently works is the better way. You're still reaping the intended benefit either way, which is audio and video with no interruptions. It's not intended to force people to watch every second without the option to skip lol

Makes sense now I guess, thank you 😁
