### ISSUE TITLE
Snapchat randomly crashes when trying to save a snap

### ISSUE THREAD

**Issue by skandaI** [rodit/SnapMod#167]
I would like to ask if I'm the only one who has this problem that randomly when I try to save a snap from context menu, the whole app freezes and only restarting helps, and the snap does not get saved. This happens to me quite regularly.

**Comment by skandaI** [comment]
Log: https://pastebin.com/m0QJDzBy
Snapchat version: 11.79.0.34 (84609)
Snapmod version: 1.7.3
Android: 11 RKQ1.200826.002 (MIUI Global 12.5.7)

**Comment by rodit** [comment]
I'm assuming this is the for the same reason as #166 but I will keep this issue open until I fix that and it's confirmed

**Comment by Magna-Graecia** [comment]
No issues here personally

**Comment by Alix8804** [comment]
> I'm assuming this is the for the same reason as #166 but I will keep this issue open until I fix that and it's confirmed

Dev my issue #166  is solved i replaced edxposed with latest riru 26.1.6 and LSposed 1.8.3 crdroid android 11 everything working fine

**Comment by Alix8804** [comment]
> Log: https://pastebin.com/m0QJDzBy Snapchat version: 11.79.0.34 (84609) Snapmod version: 1.7.3 Android: 11 RKQ1.200826.002 (MIUI Global 12.5.7) LSPosed 1.8.2 (6519) - Zygisk

I had same issue use latest riru 26.1.6 and LSposed 1.8.3 not zygisk disable show toast enable use Android dawnlaod manager in snapmod setting

**Comment by skandaI** [comment]
OK, as yet I updated to the latest version LSPosed (Zygisk) and Magisk - maybe this will solve the problem. Probably I need Zygisk to get other things working properly.

**Comment by skandaI** [comment]
I think the issue has been resolved, since the LSPosed update Snapchat has not crashed once.
