### ISSUE TITLE
Error getting Snapchat package info 

### ISSUE THREAD

**Issue by AFunkyMonk** [rodit/SnapMod#169]
I have the correct Snapchat version 11.79.0.39.
It worked then snap got auto updated and now it doesn't work :/

**Comment by jammyjay** [comment]
If your snap got auto updated, that means your no longer on the right version of snap. You need 11.79.0.34

Uninstall Snapchat, turn off automatic updates and then install the right Snapchat version from apkmirror.

**Comment by AFunkyMonk** [comment]
Oh yeah, forgot to menu i already downgraded to 11.79.0.34 again. Sorry for confusion. But it still doesn't work

**Comment by AFunkyMonk** [comment]
Now it fixed itself. I didn't do anything. It just works now...

**Comment by romhacks** [comment]
Did you reboot in between? Often I find a reboot will help it "discover" a supported version again.

**Comment by AFunkyMonk** [comment]
Yes i did. And reinstalled both Snapchat and SnapMod. Still don't know what fixed it

**Comment by rodit** [comment]
Glad you fixed it, I'm gonna close this issue as it's hard to tell what exactly the issue was and I'm not that bothered about the installation status not working sometimes.
