### ISSUE TITLE
Snapchat on 2 phones

### ISSUE THREAD

**Issue by rekdi** [rodit/SnapMod#172]
Hello,
Its not a bug, but before updating Snapchat on my iPhone🥴 i was able to be login on two phones.

Is it possible for you to do something in order to be login again on my iPhone and my Android.

iOS version : 11.80.0
Android : 11.79.0.34

When i am logged in one, it logout automatically in the other 

( if Someone knows how to downgrad on ios without jailbreak, let me know 😩)

**Comment by jkooper32** [comment]
Didn't know that was possible . I always thought Snapchat only gave you one authorization token so you were kinda forced to use the account in one device only

**Comment by rekdi** [comment]
> Didn't know that was possible . I always thought Snapchat only gave you one authorization token so you were kinda forced to use the account in one device only 

Well it worked until i updated. 🥲

**Comment by GoatBan** [comment]
You need to log on your Android first, it's still working for me

**Comment by rodit** [comment]
This is out of the scope of Snapmod.
