### ISSUE TITLE
Save problem

### ISSUE THREAD

**Issue by N0on32** [rodit/SnapMod#175]
The option to save does not appear in subscriptions and for you after updating to 1.8.0
![Screenshot_٢٠٢٢٠٦٠٢-١٧٣٥٤٠_Snapchat](https://user-images.githubusercontent.com/105910941/171654998-163bd52e-0427-4ab8-998e-741cfd9311b6.jpg)

**Comment by rodit** [comment]
Are you using the latest version of Snapchat? Did you kill and restart Snapchat twice after updating?

**Comment by N0on32** [comment]
Yes, I used the latest version 11.81, rebooted more than twice, also deleted and reinstalled Snap

**Comment by rodit** [comment]
Hmm. It's there for me - I'd recommend checking your Xposed logs for errors.

**Comment by Juuuuulie10** [comment]
Same problem here. Save option isn't showing.

**Comment by iRashiD-AE** [comment]
Same issue here , also not appear in SnapMap

**Comment by rodit** [comment]
Okay, I will look into it

**Comment by rodit** [comment]
Fixed in v1.8.1 (release will appear soon)
