### ISSUE TITLE
unknown_story file

### ISSUE THREAD

**Issue by crxed9** [rodit/SnapMod#177]
In the For You section, some stories are downloaded as a "unknown_story_xxx.mp4" file, always 1.91 kb, so not playable/corrupt.

Stories from "actual people" seem to work, but for pages like "Car Crazy" or "Good Shots", it doesn't work.

SC 11.81.0.34
SnapMod 1.8.1

**Comment by rodit** [comment]
I do not plan on fixing this - I have addressed it in a previous issue about snap map stories - please find that issue for more information.

**Comment by crxed9** [comment]
Found it: https://github.com/rodit/SnapMod/issues/82
