### ISSUE TITLE
Please download from the map is not working

### ISSUE THREAD

**Issue by alwakir** [rodit/SnapMod#181]

**Comment by alwakir** [comment]
![Screenshot_٢٠٢٢٠٦٠٢-٢٣٣٨١٣_Gallery](https://user-images.githubusercontent.com/50989902/171776085-1fd2196b-0915-4e59-94f1-f5a07b82d6c3.jpg)

**Comment by tarek133** [comment]
https://github.com/rodit/SnapMod/issues/82#issue-1227481982

**Comment by rodit** [comment]
Please see the mentioned issue - I have no plan on changing this.
