### ISSUE TITLE
Long videos from chat not being broken up in multiple snaps

### ISSUE THREAD

**Issue by jammyjay** [rodit/SnapMod#19]
Sending a long video from chat, just results in one long snap; versus the normal 10 second snaps that you see when you send long videos

**Comment by tycoon420** [comment]
> Sending a long video from chat, just results in one long snap; versus the normal 10 second snaps that you see when you send long videos

enable the option Bypass Video Length Restrictions. it should fix the problem
![photo1649772212](https://user-images.githubusercontent.com/11652113/162980299-9a1c9009-6bf4-4d8b-9bdd-173d63dfc022.jpeg)
.

**Comment by tarek133** [comment]
No it doesn't work. Videos longer than 10 seconds just won't send at all, even with that option turned on.

**Comment by tarek133** [comment]
![Screenshot_20220412-181709](https://user-images.githubusercontent.com/12681440/163007963-b75ff72f-aa38-45cf-893f-b43c7dec899f.png)
It says "videos you want to share have to be shorter than 11 seconds"

**Comment by rodit** [comment]
That option only allows you to send them from the gallery drawer in the actual chat, not from your memories/gallery from the main camera screen.

**Comment by jammyjay** [comment]
> > Sending a long video from chat, just results in one long snap; versus the normal 10 second snaps that you see when you send long videos
> 
> enable the option Bypass Video Length Restrictions. it should fix the problem ![photo1649772212](https://user-images.githubusercontent.com/11652113/162980299-9a1c9009-6bf4-4d8b-9bdd-173d63dfc022.jpeg) .

Doesn't work. It sends as one long snap. 

I don't have a problem with videos not sending. The problem is long videos just sends as one snap, instead of being broken into multiple snaps which is the normal way. So if you sent a 60 second video normally on Snapchat, it is broken into six 10 seconds long snaps. If you send a 60 second video using snapmod, it is just one snap; albeit the video sends and plays fine

**Comment by rodit** [comment]
There's not much I can do about that unfortunately. People have sent me >10 second video snaps (sometimes a whole minute) before though (without using Snapmod) so I'm not sure why they sometimes get split and sometimes don't.

**Comment by jammyjay** [comment]
Ah okay. Didn't know that was a thing. It's still working regardless if Snap breaks it up, so I guess we can close this.
