### ISSUE TITLE
Stories saving as WebP & x265

### ISSUE THREAD

**Issue by FilthyLiquid** [rodit/SnapMod#194]
Images save with the .JPG extension but they are really .WebP and video is encoded to x265.
Is there any particular reason for this? Would it be possible to add an option to save as a true .JPG and use x264?

**Comment by rodit** [comment]
They're just what is provided by default by Snapchat. This can probably be changed quite easily.

**Comment by rodit** [comment]
I'm going to close this issue as it is basically the same as the feature request #185 

Please follow that discussion for updates.
