### ISSUE TITLE
Mapping Loading

### ISSUE THREAD

**Issue by ya-v-ia** [rodit/SnapMod#2]
On android versions with scoped storage snapmod will fail to load the mappings file unless snapchat is downgraded to a version that targets android 10 and no longer uses scoped storage

**Comment by rodit** [comment]
I'm looking at fixing this now - introducing a service that Snapchat will bind to and then performing mapping/configuration reading through that service (which will run in the context of the Xposed module).

**Comment by rodit** [comment]
See pull request: #3 

Not thoroughly tested but works well on my device.

**Comment by jaqxues** [comment]
Are you open to change the way you load the mappings? Then I would pitch you the concept of loadable code bundles. Then you have a bundle for each version you want to support. An example of an application using that is Instaprefs, you can have a look if you want.

There are also tools to automate updating those bundles (similarly to what you already have, but updates are statically loaded on PC and not on the phone). My main problem is searching & updating at runtime, and it not working perfectly for some versions anyway.

**Comment by jaqxues** [comment]
Also small side-note. As soon as you introduce a content provider or service, you add a lot of additional latency. In the worst-case, the entire SnapMod application has to be cold-loaded, which can add a second or two to load times. This is not up to a specific android version, nor linked to the performance of a device itself, but rather an android scheduling "issue".

This would not be an issue by itself, but keep in mind that Android does AOT-compilation and dex optimizations. Hence, if you wait too long, most methods will be already optimized, making it impossible to hook them for Xposed Framework. This can result in endless hangs, and the target app not opening, just showing splash screens.

Try to find a way to load all your hooks immediately if possible. In your case, I suggest caching the Mappins, and checking (after loading the old ones) that mappings actually exist, or if there is a new version. If yes, copy the files, and show a dialog to the user "Do you want to apply new mappings" (or just do it programmatically).

**Comment by jaqxues** [comment]
Any more private contact options?

**Comment by rodit** [comment]
You can contact me on discord rodit#0978

For now I have just implemented mapping caching so hooks are performed immediately (pr: #5 )
