### ISSUE TITLE
Can't get the mod to work.

### ISSUE THREAD

**Issue by Allu223** [rodit/SnapMod#204]
Mod doesn't seem to work for me. I have tried every troubleshooting thing possible and still it doesn't work. What to do?

**Comment by WmeLuna** [comment]
1. make sure lsposed has snpachat enabled
2. make sure snapchat is the latest supported version (11.82.0.32)
3. in snapmod make sure it says supported
if it says it is unsupported but you have the correct version, force stop snapchat and reopen then open snapmod again
4. to provent snapchat from auto updating while still having auto-updates for other apps use [UpdateLocker](https://modules.lsposed.org/module/ru.mike.updatelocker) and add snapchat to the selected apps
