### ISSUE TITLE
Questions about some features

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#21]
I don't really get what those options are for:
- Allow Download Public DPs
- Override Gallery Snap Type
- Override Add Friend Method
- Don't Release Messages
- Log Network Requests

I'd be thankful if you could explain it in the read.me!

**Comment by rodit** [comment]
Yes - I will write proper explanations for these soon (both in the app and in the readme).

**Comment by rodit** [comment]
All the options now have summaries in the app.
