### ISSUE TITLE
Add hide icon launcher 

### ISSUE THREAD

**Issue by MohamadBayz** [rodit/SnapMod#214]

**Comment by romhacks** [comment]
android apps are required to have a home screen icon since Q I believe. This could probably be bypassed with Xposed but it doesn't seem like good practice, also how would you configure the settings then

**Comment by MohamadBayz** [comment]
I believe most of the users now uses LSposed which you can bypass the ability to hide icons, also if you hide the icon you can enter the app through LSposed module tab, so basically this way you can open all of your modules inside LSposed.

**Comment by authorisation** [comment]
This is a feature suggestion please move it to Discussions

**Comment by authorisation** [comment]
> android apps are required to have a home screen icon since Q I believe. This could probably be bypassed with Xposed but it doesn't seem like good practice, also how would you configure the settings then

I agree

**Comment by MohamadBayz** [comment]
> This is a feature suggestion please move it to Discussions

Moved it to discussion.
