### ISSUE TITLE
This is not a request or a bug.

### ISSUE THREAD

**Issue by Lucky-069** [rodit/SnapMod#224]
Hello, the repo hasn't had any updates for a month now and that's absolutely fine. Given the progress the project had earlier, either rodit is busy with life, or the project got abandoned. I just hope rodit is doing well and is just busy with work and life.. Wish him good health. You don't have to come and update the project every now and then as it's a personal project of yours that you intend to do in free time. Just wanted to know if you(rodit) is doing fine. Apologies for being so cliché

**Comment by Lucky-069** [comment]
Has anyone heard from rodit? @jbnitro are you aware of anything?

**Comment by rodit** [comment]
Thanks for asking, I'm doing great! Just busy with work and life as you say. SnapMod won't see any updates for a couple of months at least but I hope to resume and update development maybe in October.

**Comment by Lucky-069** [comment]
> Thanks for asking, I'm doing great! Just busy with work and life as you say. SnapMod won't see any updates for a couple of months at least but I hope to resume and update development maybe in October.

I don't have any issues with no updates. Just wanted to check on you, since snapmod already is good and doesn't even needs any updates!
