### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by CoolGuyMK** [rodit/SnapMod#228]
Can u try to add dark mode too?

**Comment by Lucky-069** [comment]
You can just use swift installer. It has dark mode on snapchat. Been using it for months now!

**Comment by CoolGuyMK** [comment]
> 

Which android version are u on?

**Comment by CoolGuyMK** [comment]
> You can just use swift installer. It has dark mode on snapchat. Been using it for months now!

I don't think it works for Android 12 right?

**Comment by Lucky-069** [comment]
You can try tho. And see if it works. It does work for some

**Comment by CoolGuyMK** [comment]
> You can try tho. And see if it works. It does work for some

![Screenshot_20220805-225311_Swift Installer](https://user-images.githubusercontent.com/63323163/183160992-fb6f4f0f-b879-4d19-a51c-68e497cf61dd.png)

**Comment by Lucky-069** [comment]
You are out of luck mate!

**Comment by CoolGuyMK** [comment]
> You are out of luck mate!

Yeah I guess so
No other substratum themes would work?

**Comment by Linux123123** [comment]
A somewhat working dark theme (with a few bugs) can be achieved using [Darq](https://github.com/KieronQuinn/DarQ/releases/download/2.2.1/DarQ-v2.2.1.apk).

**Comment by authorisation** [comment]
https://github.com/rodit/SnapMod/discussions/111
