### ISSUE TITLE
Snap save story save DP safe not showing in filemanager

### ISSUE THREAD

**Issue by Alix8804** [rodit/SnapMod#24]
I enable allow saving snap allow download stories allow Public profile DPs on 3dot save option appear but when I press save I can't see vid pic in any folder story DP picture streak from friends none working only long press save to camera roll  from freinds streak picture video working for me please guide how to save stories and DP and streak with save button

**Comment by rodit** [comment]
The saved media should be in `Internal Storage/Movies/SnapMod/...` by default.

**Comment by Alix8804** [comment]
I delete and reinstalled snapmod default story path is
$Movies/SnapMod/%u_story_%t
Still no Movies folder in my file manager please tell me if path is good why snapmod not generating movies folder 
When I enable allow save stories save button epaer in option but saving story not working should I factory reset my phone or something wrong with path address

**Comment by rodit** [comment]
No - don't factory reset, that won't fix it. It's probably a bug - could you gather the logcat output for me (for xyz.rodit.snapmod)?

**Comment by rodit** [comment]
Didn't mean to close this issue.

**Comment by jammyjay** [comment]
Actually seeing the same issue. Stories not saving and no internal folder that SnapMod alludes to present. Even changing the save folder, stories still aren't showing up.

**Comment by rodit** [comment]
@jammyjay what version of Android are you using?

**Comment by jammyjay** [comment]
> @jammyjay what version of Android are you using?

I'm on Android 9

**Comment by Alix8804** [comment]
I don't know what is logcat output is
Folder you mentioned Android data xyz.rodit.snapmod there is nothing except folder name file
But in root data data xyz.rodit.snapmod there are two file
1/data/data/xyz.rodit.snapmod/shared_prefs
xyz.rodit.snapmod_preferences.xml
2 /data/data/xyz.rodit.snapmod/files
84586.json
But I don't know how to post them here send me your email I well send these file to you if you need these to fix bug

**Comment by rekdi** [comment]
Me too, i dont see the folder
How can i can send you the log?

**Comment by Alix8804** [comment]
Updated my phone from lineage Android 7.12 to Android 11 everything working fine now

**Comment by rodit** [comment]
I assume it's a storage issue pre Android 10 - what I would recommend is turning off the 'Use Android Download Manager' option if you are using < Android 10.

**Comment by rodit** [comment]
@jammyjay and @rekdi Please try disabling 'Use Android Download Manager' in the settings and let me know if that fixes it.

**Comment by rekdi** [comment]
Actually, i am on Android 11, and it was already disabled. I enabled it and it works. THANKS

**Comment by jammyjay** [comment]
Datapoint - It did not fix it for me, so I simply upgraded to Android 10. Now it works fine.
