### ISSUE TITLE
Not a feature or bug! 

### ISSUE THREAD

**Issue by Lucky-069** [rodit/SnapMod#246]
Just came across this new post on xda, thought it can somehow be useful for snapmod (or maybe not) but I'll just share it here
[Dexfile](https://forum.xda-developers.com/t/dexplore-lib-obfuscated-code-finder-develop-portable-xposed-module-for-obfuscated-apps.4477899/#post-87259237)
This can be used to develop xposed modules without having to worry about the app changes that take place. The module would take care of the obsuficafion!

**Comment by authorisation** [comment]
Thank you so much this might actually help

**Comment by rodit** [comment]
This just looks like dexsearch with a lot less features

**Comment by Lucky-069** [comment]
It is definitely useful, since the dev has just started and it working on it pretty much

**Comment by RevealedSoulEven** [comment]
Hmmm. Looks great! Something similar was being used by me in past to mod Il2cpp unity games where we used only class name and methods instead of the hex addresses.
Really Great

**Comment by authorisation** [comment]
Now that Snapmod got updated mind closing this?
