### ISSUE TITLE
The discovery is still invisible 

### ISSUE THREAD

**Issue by RSR1337** [rodit/SnapMod#249]
First of all, thanks for the update and great work 

This bug has been reported since version 1.8.3 but is still present in the new update 

![Screenshot_20220923-191440_Snapchat](https://user-images.githubusercontent.com/52901789/191995751-730d198f-74d8-48b2-9d39-589bf894fcf6.png)

It can be fixed by select ( for you ), but the discovery section remains invisible

**Comment by authorisation** [comment]
I don't know if the LSPosed Logs contain relevant information but could you please upload them?

**Comment by RSR1337** [comment]
> I don't know if the LSPosed Logs contain relevant information but could you please upload them?

[LSPosed_2022-09-23T19_39_24.831.zip](https://github.com/rodit/SnapMod/files/9635097/LSPosed_2022-09-23T19_39_24.831.zip)

**Comment by RSR1337** [comment]
Try this one 

@authorisation 

[LSPosed_2022-09-23T19_42_15.053.zip](https://github.com/rodit/SnapMod/files/9635122/LSPosed_2022-09-23T19_42_15.053.zip)
