### ISSUE TITLE
Addition of a feature  - Paid

### ISSUE THREAD

**Issue by easystealth** [rodit/SnapMod#25]
Hi,

I would like to talk to you regarding of addition of some private features in this repository for which I would like to pay you well for your time as well. If you are interested please contact me here :
Telegram : @stealtheasy
Discord : easystealth#3081
Email : jayseen238@gmail.com

**Comment by alwakir** [comment]
thank you
Snap Mod working good

**Comment by rodit** [comment]
Sorry, I am not interested.

**Comment by easystealth** [comment]
Thank you! You could have just said that instead of blocking me.

**Comment by easystealth** [comment]
Hey there,

My name is Sam. Nice to meet you.
