### ISSUE TITLE
Fails to get snapchat package info 

### ISSUE THREAD

**Issue by PHATWalrus** [rodit/SnapMod#259]
![Screenshot_20220925-210106_SnapMod](https://user-images.githubusercontent.com/76208242/192152005-6f6ffa65-b8d4-45cc-83df-7f66497f0248.jpg)

**Comment by us3rname101** [comment]
Have enabled SnapMod in LSPosed?

**Comment by RevealedSoulEven** [comment]
Switch between snapchat and snapmod a couple of times, you'll fix it somehow

**Comment by Lucky-069** [comment]
First open the snapmod, and then open snapchat & force close it. Open the snapmod again and viola it should work for you. 🤦‍♂️ This was literally mentioned in readme
