### ISSUE TITLE
thank you 

### ISSUE THREAD

**Issue by alwakir** [rodit/SnapMod#26]
welcome
Snap Mod working good

**Comment by easystealth** [comment]
If you didn't wanted to work you could have just said so instead of just blocking me

**Comment by rodit** [comment]
I appreciate it but please do not use this for general comments. @easystealth I did not block you?

**Comment by easystealth** [comment]
Yes you blocked me on telegram after I messaged and then you also unadded
me from discord as well.

**Comment by rodit** [comment]
@easystealth I don't have telegram? You were probably being scammed lol.

**Comment by rodit** [comment]
I also didn't receive any friend request from you on discord so be careful, I would let you know on here before I contact you.

**Comment by easystealth** [comment]
Someone else must have contacted me then. Apologies for the comment then,
if you are ever interested tho I will like to pay you very well and will
have constant work if you would like that as well.

**Comment by rodit** [comment]
Thanks, I'll let you know - please be weary of people impersonating me. I'll always give my details out and asked to be contacted.

**Comment by easystealth** [comment]
Ok, thanks. Let me know if you are ever interested or knows someone else
who might be interested. I am always looking to expand my team.

**Comment by easystealth** [comment]
I could not find your discord @ but I had a incoming request from someone
but when I told them what i wanted they blocked me on telegram and then
unadded me from discord as well.
