### ISSUE TITLE
You should add pinning of users similar to ios.

### ISSUE THREAD

**Issue by JReverse** [rodit/SnapMod#27]
I feel this is possible although I never attempted on latest.

Also a dark mode would be nice.

**Comment by rodit** [comment]
Pinning is something I've started looking at - shouldn't be too difficult. Dark mode is less interesting to me so I might not look at that for a while.

**Comment by Lucky056** [comment]
@JReverse @rodit I would suggest using swift installer. It supports dark mode and you can get amoled theme on snapchat using that! Do try

**Comment by rodit** [comment]
Just added pinning conversations (1.4.0)

**Comment by tarek133** [comment]
> Just added pinning conversations (1.4.0)

How do you use this feature? I didn't see any option to pin the chat even though I enabled the setting for it.

**Comment by rodit** [comment]
Make sure you kill Snapchat and relaunch twice after updating. Hold down on the chat (group chats aren't currently supported) and toggle the Pin conversation option.
