### ISSUE TITLE
Subscriptions Stories + Snaps (via Chat tab) issues

### ISSUE THREAD

**Issue by conloi** [rodit/SnapMod#28]
Hi there,

Saved stories from Subscriptions show `%u` in the filenames.

Friend stories are fine, I can only see this issue with Subscription Stories.

**Comment by conloi** [comment]
Same `%u` appears in filenames when you save snaps (the ones opened via Chat tab).

**Comment by rodit** [comment]
This is fixed in the next release (1.4.1). Stories downloaded from public profile pages (i.e. the actual profile page, not your subscriptions or discover feed) however will show 'unknown' instead of the username (it's seemingly impossible to find the username when saving them).
