### ISSUE TITLE
Automatically Save Stories

### ISSUE THREAD

**Issue by clublek** [rodit/SnapMod#33]
Will there be a feature which will automatically save stories when viewed?

**Comment by jammyjay** [comment]
Seems unnecessary. Not everyone wants to save every single story they view and saving the ones you want, is easy enough as it is now.

**Comment by ObscenityIB** [comment]
how DO you even save them, i have every switch turned on and nothing saves, using latest version with the same version supported in that release

**Comment by ObscenityIB** [comment]
ive tried holding tapping on the story, but theres no button or anything that says save
