### ISSUE TITLE
Story save issue with Android 8

### ISSUE THREAD

**Issue by thracianx** [rodit/SnapMod#40]
Please include a fix for saving story snaps on android 8(oreo) in the next update, I tried changing story download path and toggling the 'Use Android Download Manager' option but nothing seems to work. Other users seem to have solved it by upgrading to android 9 or 11 but I can't do it on mine so a fix for Oreo would be appreciated. thanks.

**Comment by rodit** [comment]
Try _without_ 'Use Android Download Manager' enabled and manually enabling storage permissions for SnapMod in the system settings app.

**Comment by thracianx** [comment]
Tried enabling storage permissions and un-ticking the Android Download Manager option but still no luck. I don't know if a notification shows up saying story has been saved like there is for saving direct snaps but if there is, I don't get that either.

**Comment by snaphappy1** [comment]
I'm running snapmod on Oreo 8.1 using the original xposed and it's running perfectly. There is no notification when a story is saved. Try re-installing snapmod and manually enabling storage permissions before changing any option. Also before your first run, make sure there is a bindings.json (renamed with sc build number) in either data/data/zyz.rodit.snapmod/files or in Andorid/data/zyz.rodit.snapmod/files if not, then manually place it there.

**Comment by thracianx** [comment]
> I'm running snapmod on Oreo 8.1 using the original xposed and it's running perfectly. There is no notification when a story is saved. Try re-installing snapmod and manually enabling storage permissions before changing any option. Also make sure there is a bindings.json (renamed with sc build number) in either data/data/zyz.rodit.snapmod/files or in Andorid/data/zyz.rodit.snapmod/files if not, then manually place it there

I'm on 8.0. I'll try out your suggestions and see if that makes it work

**Comment by rodit** [comment]
Logcat output would help greatly in diagnosing why it doesn't work - you can get the logcat output by first running `adb shell pidof -s xyz.rodit.snapmod` in your terminal/command prompt/powershell with your device connected. This will output a number. Then run `adb logcat --pid=X` where `X` is the number output from the first command. Then try and download a story and copy anything that shows up in your terminal and paste it here.

**Comment by thracianx** [comment]
can't run the adb command because my phone won't connect to any PC, it's been that way for a while, an issue with the phone port maybe. Anyway I guess it's okay to close this issue for now, I'll try tweaking with the settings and see if I can get it sorted out. Thanks.

**Comment by thracianx** [comment]
Tried on my own to fix this issue but no dice but I was wondering since saving snaps works, if it was possible to set the story download destination to the same folder path as savings snaps(which in my case is '/storage/emulated/0/snapchat'). If there was a file to edit a file or change any settings, I could probably see if this works.
