### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by pesketo** [rodit/SnapMod#42]
Everytime when you bring out an update I cant install the apk it says app not installed and I have to manually delete the old app and install new apk is this a known issue? Or is it me.

**Comment by rodit** [comment]
Ill try and setup consistent signing for the next release. After reinstalling that, all future installs should be fine.

**Comment by pesketo** [comment]
I just tried installing 1.4.1 still the same issue.

**Comment by rodit** [comment]
Yes, all future versions (>1.4.1) should no longer have the issue.
