### ISSUE TITLE
Only public profile stories saving

### ISSUE THREAD

**Issue by pesketo** [rodit/SnapMod#43]
Friend stories and private messages are not being saved 1.4.0 (11.74.1.30). I'm on android 11 and android download manager is ticked.

- It was working fine before on older update.

**Comment by rodit** [comment]
I need logs

**Comment by pesketo** [comment]
Where are the logs saved?

**Comment by rodit** [comment]
LSPosed manager has a logs tab.

**Comment by pesketo** [comment]
https://drive.google.com/file/d/1G0xZOS-moH3Az0bQC_BJuMrO5ZKrAu8r/view?usp=drivesdk

**Comment by pesketo** [comment]
Suddenly it works again
