### ISSUE TITLE
"For You" section - possible to disable/hide?

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#48]
Would it also be possible to have this section removed? I already enabled the "block ads"  and "disable spotlight" settings.
![Screenshot_20220419-203517](https://user-images.githubusercontent.com/12681440/164072397-16f9af16-9d54-418e-b68d-e586f5095c3e.png)

**Comment by rodit** [comment]
Yeah I hate that section lol - I'll probably add an option to remove it soon ish.

**Comment by rodit** [comment]
You can now disable this in 1.4.4 with the 'Hide Story Sections' option (checking the 'For You' suboption).
