### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#49]
Have you thought about adding a donation link (e.g. paypal) to the repo? I'd happily support you and this project! :)

**Comment by JReverse** [comment]
Add crypto addy's to.

**Comment by rodit** [comment]
I have added some donation options to the readme - please understand that I by no means need the donations, but it is definitely a motivator to see people appreciating the work. You are, of course, under no obligation to donate anything - SnapMod will always be completely free to use and open source.
