### ISSUE TITLE
Mappings not downloaded

### ISSUE THREAD

**Issue by eddywitkamp** [rodit/SnapMod#51]
Version 1.4.2

After opening the app for the first time after install, a window pops up telling you to download the bindings.
After I press download, I see a toast message "bindings successfully installed".

But the /files folder is empty and when pressing the Save button on a snap, Snapchat hangs and shows a "Snapchat not responding" window.

I didn't have this experience with version 1,3 where everything worked as expected.

Could it be because SnapMod is not asking for Storage permission?

[ 2022-04-20T18:11:17.409    10300: 16744: 16744 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~kfXb1KnZUV0NJwTT1xYVyg==/xyz.rodit.snapmod-9-Smgxx8U1U9oSGAuFDLIg==/base.apk
[ 2022-04-20T18:11:17.462    10300: 16744: 16744 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-04-20T18:11:17.690    10300: 16744: 16744 I/LSPosed-Bridge  ] Context hook com.snap.snapchat.shell.MushroomAppShell@d87f9f0, [android.app.ContextImpl@a2d25a2]
[ 2022-04-20T18:11:17.803    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias FriendsFeedRecordHolder. No mapping found.
[ 2022-04-20T18:11:17.805    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias FriendChatActionMenuBuilder. No mapping found.
[ 2022-04-20T18:11:17.805    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias FriendChatActionHandler. No mapping found.
[ 2022-04-20T18:11:17.805    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias ProfileMyFriendsSection. No mapping found.
[ 2022-04-20T18:11:17.806    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias FriendListener. No mapping found.
[ 2022-04-20T18:11:17.806    10300: 16744: 16744 I/LSPosed-Bridge  ] Cannot hook class with alias CompositeConfigurationProvider. No mapping found.
[ 2022-04-20T18:11:17.807    10300: 16744: 16744 I/LSPosed-Bridge  ] Loaded cached mappings for build 84586.
[ 2022-04-20T18:11:17.858    10300: 16744: 16744 I/LSPosed-Bridge  ] Configuration server failed to find valid mappings.

**Comment by eddywitkamp** [comment]
I uninstalled 1.4.2 and installed 1.3.1 again and everything works immediately.
The Android /files folder is still empty though....

**Comment by rodit** [comment]
As stated in the readme, you have to forcefully kill and restart Snapchat twice after installing new mappings. When installed from the app, they are installed to the modules private files directory not in Android/.../files so that's why you don't see the file there.

**Comment by eddywitkamp** [comment]
Of course I killed Snapchat, more than once. It even closed more than twice because it was Not Responding and had to Force Close it. Still does not work.
