### ISSUE TITLE
Request: Show supported version of SC in app

### ISSUE THREAD

**Issue by eddywitkamp** [rodit/SnapMod#52]
Continuation of https://github.com/rodit/SnapMod/issues/51

The sole reason why my previous install of SnapMod was not working (No mapping found) was because apparently the supported version of Snapchat got updated to a higher version, 4 builds ago.

If the supported version of SC is shown in SnapMod somewhere, it will be more easily known when to update SnapChat.

Thanks.

**Comment by rodit** [comment]
I will add a more obvious way of telling if the current version of Snapchat is supported within the app - for now, I'd suggest turning off auto update in the play store for Snapchat.

**Comment by eddywitkamp** [comment]
My Snapchat didn't get updated, but I updated SnapMod.
So SnapMod was "too new" for my older SC.

So yeah, any way of telling which versions to combine is good.

**Comment by rodit** [comment]
1.4.4 now shows the latest installed version and whether any mappings were found for it at the top of the SnapMod settings app.

**Comment by degsyh** [comment]
Would be good also to see what current version of SnapMod you are running at the top as well 😊
