### ISSUE TITLE
Bypass video length restrictions not working

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#53]
Whenever I try to send a video longer than 10 seconds from the gallery drawer within snapchat, it gets sent as a chat, not as a live snap. Even though I enabled the option in SnapMod. Tried force closing 2 times as suggested, but still no fix. 
Videos that are maximum 10 seconds long send just fine.

**Comment by tarek133** [comment]
Screen Recording that shows the issue:
https://streamable.com/5p1k8i

Picture of settings:
![Screenshot_20220421-005002](https://user-images.githubusercontent.com/12681440/164337483-bce2357b-9339-4122-b04d-45aa65f2d8b0.png)

**Comment by rodit** [comment]
Yes, this is expected, you have to send the video from within the actual chat (i.e. click the gallery icon next to the message input textbox) for this to work at the moment.

**Comment by tarek133** [comment]
Ah got it, thanks for clarifying.
