### ISSUE TITLE
Possibility to add option to disable Snap Map and Discover Tab

### ISSUE THREAD

**Issue by jkooper32** [rodit/SnapMod#54]
Would it be possible to add the option to disable the snap map and discover tab? Maybe a few users like me don't really use them and was wondering if that is possible and doesn't take too much work. THanks!

**Comment by rodit** [comment]
You can disable the discover tab by enabling the disable spotlight option (I'll rename this to discover in the next update, as I believe spotlight is actually some other part of the app). I'll see about disabling other tabs too.

**Comment by jkooper32** [comment]
Just downloaded the latest version and the "for you" tab and "subscriptions" are now hidden - so thank you for that, awesome work !! 

One issue I've noticed -  Sometimes the discover tab still comes up as the three parallel lines on the snapchat app. Sometimes the spotlight icon (the triangle) still comes up but when you click it it will say that the page is not available which is good. 

Was wondering if the discover tab/spotlight triangle tab could be hidden for good? 

Sometimes when you go to the friends tab and swipe right - the discover tab comes up and was wondering if that can be eliminated for good. 

Probably you are still looking into it but it'd be nice to have the option to disable the "snap map" (location icon) tab also since maybe a few users like me don't use it and it's just an annoyance to swipe or go into that tab by mistake. 

Thanks for all the awesome features thus far!
