### ISSUE TITLE
Anonymous story viewing is not working

### ISSUE THREAD

**Issue by snaphappy1** [rodit/SnapMod#55]
First off, thank you for this great mod! So I've messaged a few of my friends, each said they can see my view on their story. It's not working for either public or private stories. I'm also wondering if this feature, when working properly, applies to regular snaps too? If not then that would be a cool thing to add, assuming its not too difficult to implement.

I'm using sc 11.75.0.33 with version1.4.3 of SnapMod
I've tried with 11.74.1.30/1.4.2 as well, same results.

I'm happy to report anonymous chat viewing (hide read receipts) works along with everything else except snap replay hiding which has never worked for me.

**Comment by rodit** [comment]
Thanks for reporting this - I'll have another look in the next update.

**Comment by rodit** [comment]
@snaphappy1 please try it in 1.4.4 - I've tried a different method and would like to know if it worked.

**Comment by jammyjay** [comment]
Just tried it in 1.4.4. Still not working. Tried it with both local and main story mode hidden together and just local only hidden.

**Comment by Magna-Graecia** [comment]
I can confirm that it was also not working for me previously, but after today's update with both "Anonymous Story Viewing" and the new "Ignore Story Viewing (Local)" feature enabled, it now works 100%.

**Comment by jammyjay** [comment]
> I can confirm that it was also not working for me previously, but after today's update with both "Anonymous Story Viewing" and the new "Ignore Story Viewing (Local)" feature enabled, it now works 100%.

Which version of Android and Snapchat are you using?

**Comment by Magna-Graecia** [comment]
@jammyjay Android 8.1.0 and latest Snapchat 11.75.0.33
