### ISSUE TITLE
how the app works

### ISSUE THREAD

**Issue by jbnitro** [rodit/SnapMod#6]
Hello,

When you check "Allow saving Snaps" do the snaps download automatically or do you have to do something in Snapchat ?
Where are the saved snap or video on phone ?

I think this app works because i can disable camera and send gallery as snap, I did not test the other parameters
What xposed do we need?
I have latest LSPosed 1.8.0 (6482) with riru 

Thanks

**Comment by rodit** [comment]
Just long press the snap in chad and press 'Save to camera roll' and it will save it wherever it would normally be saved (usually /Snapchat). Stories and audio notes are saved in /Movies/SnapMod.

**Comment by rekdi** [comment]
Hello,

I have a one plus 3T and i don't see the option "Save to camera roll" I can screenshot the conversation without the warning message but, I don't see any option to save. And I did tick the option save snaps
