### ISSUE TITLE
Snapchat crashing after 1.5 update

### ISSUE THREAD

**Issue by edi194** [rodit/SnapMod#64]
Phone: Xiaomi Mi9
ROM: PixelExperience 12
Xposed: Riru+Lsposed (Magisk 23.0)

Snapchat starter to crash after 1.5 update, I've tried clean installing it but it didn't helped. Cleaning Snapchat and/or SnapMod data didn't worked.

Lsposed log:
[modules_2022-04-26T17:58:40.586.log](https://github.com/rodit/SnapMod/files/8564981/modules_2022-04-26T17.58.40.586.log)

**Comment by rodit** [comment]
Just fixed this, try 1.5.1 when it publishes.

**Comment by edi194** [comment]
Now it is working correctly on 1.5.1, thanks 👌
