### ISSUE TITLE
Send as gallery

### ISSUE THREAD

**Issue by pesketo** [rodit/SnapMod#66]
Send as gallery doesn't send as snap but as chat

**Comment by Magna-Graecia** [comment]
One thing I will say is make sure "Gallery Snaps Time Limit" has a number in it. I noticed that if it was set to 0 and I sent from gallery drawer, it would show the timer circle in the photo but it would be empty like it ran out, and I didn't like this, so I deleted the 0 and kept it blank. This broke "Send Gallery as Snaps" and caused all snaps to be sent as chats. So make sure you have a number in that box.

My solution to this was to send photos by sharing from gallery to Snapchat, not using the in-chat gallery drawer. When doing this, the timer bubble wouldn't show on photos. Strange, but it works.

The only other thing I can say is to make sure your Snapchat version is 11.75.0.33, and make sure you have both killed Snapchat twice by going into settings and selecting 'Force Stop', and also do a full reboot of your device. And of course make sure you have "Send Gallery as Snaps" enabled in SnapMod settings haha. If it still doesn't work after all this, then something else is going on and rodit will have to look into it.

**Comment by jammyjay** [comment]
I feel like this might be simple as Do you have "Send Gallery as Snaps" enabled.

**Comment by rodit** [comment]
> Send as gallery doesn't send as snap but as chat

Please do not post issues like this...

**Comment by pesketo** [comment]
> > Send as gallery doesn't send as snap but as chat
> 
> Please do not post issues like this...

It really doesn't work it's enabled in snapmod
