### ISSUE TITLE
[Question] New snapchat versions compatible?

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#67]
So I didn't really understand how it works when Snapchat gets updated but SnapMod didn't yet.
Is it likely that SnapMod will work with a newer version of snapchat too?

**Comment by jammyjay** [comment]
There is zero reason to update Snapchat or any app/game for that matter; if something your using for a app/game, is only specified to knowingly work for a specific version. You can freely test it out yourself to see if it works, but that is on you. This goes for any add-on for a game or app.

This isn't really a Issue.

**Comment by rodit** [comment]
SnapMod will not work at all without me updating it for new versions of Snapchat  (with the exception of disabling the camera).
