### ISSUE TITLE
Nothing Important 

### ISSUE THREAD

**Issue by Lucky-069** [rodit/SnapMod#69]
This sounds selfish but would it be possible to have a discord server or a telegram group. Because we all are aware at some point the app might die due to snapchat coming with legal bs. So if you wish to continue (I hope you do for the closed group) that's how most anime apps and there's another mod of snap that's only for its discord members. Because it would hurt not being able to live without the mod in future :(
So if anything happens. You can archive the repo and work on the project privately as you said you really enjoy working on this project! And we love using it so :)

**Comment by rodit** [comment]
I really do not have time to manage a discord server/telegram page, especially when people have the lack of respect to start endlessly messaging me directly, asking ridiculous questions as if I have nothing better to do than answer them lol (I know this seems rude but I have plenty experience of this in a handful of previous projects I have made public).

I appreciate your kind words and I'm glad you like using SnapMod, I do indeed enjoy working on it :). That said, if anything legal happens I will stop working on the project anyway, so there is no point of keeping contact through a discord/telegram channel. I do not plan to secretly distribute updates if I am legally required not to.
