### ISSUE TITLE
After viewing a snap, I only can replay the snap instead of getting the context menu

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#71]
What I noticed with trying to save snaps immediately AFTER you viewed them:
Sometimes, it gives you the option to long press the viewed snap in chat and then there will be the context menu where you can either choose to replay it, delete it, or save it to camera roll. It won't automatically replay the snap though, which is good.

But very often I somehow only get the classic option to replay the snap after I viewed it. There won't be a menu from where I can choose what to do with it. When I long press the viewed snap, it just replays and sends the notification out, even though its disabled.

Some info:
**Device**: OnePlus 8 Pro, Android 11 
**LSPosed version**: 1.8.2
**Magisk Version:** 23
**Snapchat version**: 11.75.0.33
**SnapMod version**: 1.5.2

I also included a log: https://krakenfiles.com/view/DQhUkRmALf/file.html

**Comment by rodit** [comment]
I cannot seem to recreate this with any kind of snap (I tried with video/image snaps both limited and unlimited duration). When you hold to replay, don't actually replay it (don't tap on it once the square fills up again). Just hold again and save to camera roll.

**Comment by tarek133** [comment]
> I cannot seem to recreate this with any kind of snap (I tried with video/image snaps both limited and unlimited duration). When you hold to replay, don't actually replay it (don't tap on it once the square fills up again). Just hold again and save to camera roll.

That's so weird because I don't get this context menu where I can choose if I either want to replay, or to save to camera roll. It only lets me replay the snap.
See my sr for reference: https://streamable.com/xe1zdg

**Comment by rodit** [comment]
What happens if you hold down on it after you hold to replay (instead of tapping)?

**Comment by tarek133** [comment]
> What happens if you hold down on it after you hold to replay (instead of tapping)?

Well after I replayed the snap I can hold down to save to camera roll. But at this point the replay notification was sent out already ofc.
