### ISSUE TITLE
[Feature Request] Decide in which folder snaps will be saved

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#74]
Right now the folder where saved snaps will be placed is the default Snapchat folder.
I think it's bad, since Snapchat Memories that you download will be saved in there too and if you do that quiet often, those memories will get mixed up with your saved snaps.

Please add an option so anyone can decide where the saved snaps will be placed.

**Comment by rodit** [comment]
Added in 1.5.4 (see 'Enable Custom Snap Download Path' and 'Set Snap Download Path' options).
