### ISSUE TITLE
Latest release 1.5.3 not working with snapchat

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#77]
I just installed the new SnapMod update, and updated SnapChat to the supported version (11.76.1.34) as well.
I installed the mappings within SnapMod as always, killed snapchat two times afterwards, but it just won't work/install. 
Keeps saying the version is unsupported even though I made sure everything is alright. I tried to reboot, disabled/re-enabled the module within LSPosed but nothing worked.

![Screenshot_20220430-180035](https://user-images.githubusercontent.com/12681440/166113204-20b1dbb1-0768-4ae0-8acd-7b5662c2f095.png)

**Comment by tarek133** [comment]
@rodit the folder shows a different version, not the 84600 one. I tried deleting it and reinstalled through SnapMod, but it always loads the 84591 in. 
![Screenshot_20220430-181421](https://user-images.githubusercontent.com/12681440/166113552-5fc5677c-e21d-45b8-b838-cdd3021640f6.png)

**Comment by iRashiD-AE** [comment]
> I just installed the new SnapMod update, and updated SnapChat to the supported version (11.76.1.34) as well. I installed the mappings within SnapMod as always, killed snapchat two times afterwards, but it just won't work/install. Keeps saying the version is unsupported even though I made sure everything is alright. I tried to reboot, disabled/re-enabled the module within LSPosed but nothing worked.
> 
> ![Screenshot_20220430-180035](https://user-images.githubusercontent.com/12681440/166113204-20b1dbb1-0768-4ae0-8acd-7b5662c2f095.png)

Rename json file to 84600.json

**Comment by tarek133** [comment]
> > I just installed the new SnapMod update, and updated SnapChat to the supported version (11.76.1.34) as well. I installed the mappings within SnapMod as always, killed snapchat two times afterwards, but it just won't work/install. Keeps saying the version is unsupported even though I made sure everything is alright. I tried to reboot, disabled/re-enabled the module within LSPosed but nothing worked.
> > ![Screenshot_20220430-180035](https://user-images.githubusercontent.com/12681440/166113204-20b1dbb1-0768-4ae0-8acd-7b5662c2f095.png)
> 
> Rename json file to 84600.json

Yes that worked, but as soon as I open SnapMod it will prompt me with the (false) mapping installation pop up again.

**Comment by tarek133** [comment]
Also story saving and some other features don't work anymore.

**Comment by iRashiD-AE** [comment]
> 

Everything is working , just keep it like this until rodit
![Screenshot_20220430-203105_MT Manager~2](https://user-images.githubusercontent.com/52901789/166114248-e06b3032-76d9-4bec-bd5f-61f09cc18435.png)
 fix it

**Comment by tarek133** [comment]
Yes it works, still saving Stories isn't working anymore. I don't know why

**Comment by tarek133** [comment]
Saving within this screen (snap & story) doesn't work anymore. Only snap saving from the chat works.
![Screenshot_20220430-185351](https://user-images.githubusercontent.com/12681440/166114953-fd8b887d-2add-4d71-ae6f-09850e871f61.png)

Log: https://krakenfiles.com/view/5IqrXzc4ZJ/file.html

**Comment by iRashiD-AE** [comment]
> Saving within this screen (snap & story) doesn't work anymore. Only snap saving from the chat works. ![Screenshot_20220430-185351](https://user-images.githubusercontent.com/12681440/166114953-fd8b887d-2add-4d71-ae6f-09850e871f61.png)
> 
> Log: https://krakenfiles.com/view/5IqrXzc4ZJ/file.html

Working...
![Uploading Screenshot_20220430-205657_Snapchat.png…]()

**Comment by tarek133** [comment]
Hm not for me anymore. It was working fine with 1.5.2 but now I can't save any story anymore.

**Comment by rodit** [comment]
I forgot to update the build number - a new release will appear shortly (still called v1.5.3). Just install the new mappings from the Snapmod app.
