### ISSUE TITLE
Saving structure 

### ISSUE THREAD

**Issue by No-WaY-SA** [rodit/SnapMod#80]
Hello, 
I'm enjoying snapmod alot , but can saving structure can be acquired from snaptool?
Like -- stories,  chat each in separate folder and within each main category the saved snap to be sorted by folder of each user by its name.

**Comment by rodit** [comment]
You can modify the download locations yourself (see the 'Story Download Path' and related options). `%u` is substituted with the username so something like `$Movies/SnapMod/%u/story_%t` will place stories in a folder named after the poster of the story. Sometimes, the username cannot be or is incorrectly retrieved though (see #15 ).

**Comment by No-WaY-SA** [comment]
Ok thanks for reply, but if i change it, it will change all saving form any user to that folder because i can't found change download path for each user or public stories, is it correct?
Can not be automated like in snaptool below 
![Screenshot_20220505-070448_Root Explorer](https://user-images.githubusercontent.com/68426919/166862278-3fa5daaa-ed3c-4c61-af11-e271377584dc.jpg)

And file naming to be formated like this
[User]_[2020-10-17_00-26-30-976.Story.*
So it contain user name and date and type of saving ( stories, chatmedia , sent , received) as in snaptools?

Appreciate your hard work and support

**Comment by No-WaY-SA** [comment]
Or can you import the whole saving code from snaptool to snapmods?
