### ISSUE TITLE
Hide replay notification 

### ISSUE THREAD

**Issue by rekdi** [rodit/SnapMod#81]
Hello,
Is that me or that option is not on the Last version anymore ?

**Comment by tarek133** [comment]
It never worked but you can replay a snap and then save it to camera roll. The notification only gets sent out when you actually view the replayed snap.

**Comment by iRashiD-AE** [comment]
> It never worked but you can replay a snap and then save it to camera roll. The notification only gets sent out when you actually view the replayed snap.

Can you pls download snap from SnapMap and see if you can play the video, for some reason downloaded snap SnapMap is broken for me

**Comment by rekdi** [comment]
> It never worked but you can replay a snap and then save it to camera roll. The notification only gets sent out when you actually view the replayed snap.

Thats my problem, i dont want people knows that i played twice their snaps

**Comment by Magna-Graecia** [comment]
> > It never worked but you can replay a snap and then save it to camera roll. The notification only gets sent out when you actually view the replayed snap.
> 
> Can you pls download snap from SnapMap and see if you can play the video, for some reason downloaded snap from SnapMap is broken for me

Here is what you do, bro: Open the video from SnapMap, tap the 3 dots in the upper right-hand corner to get the context menu like you normally would to save, but instead of tapping save, tap "Send Snap" and send it to yourself. From there, save like normal and you will be able to play it. This is how I save snaps from SnapMap.

**Comment by Magna-Graecia** [comment]
> > It never worked but you can replay a snap and then save it to camera roll. The notification only gets sent out when you actually view the replayed snap.
> 
> Thats my problem, i dont want people knows that i played twice their snaps

That's what he's saying. You can view the snap without them getting a notification. When you press and hold on a snap to replay it, and it refills, they don't get a notification until you actually view the snap again. So don't view the snap after you pressed and held to replay it. Simply go into the chat by pressing the chat bubble on the right-hand side of the chat, then press and hold on the snap while in the chat to get the context menu where you can select "Save to Camera Roll". Then you can save it and view it, and they will never receive any notification. Make sure "Hide Saved to Camera Roll" is enabled in SnapMod settings.

**Comment by rodit** [comment]
You can also enable stealth mode or the global 'Hide Snap Views' option to disable all snap interaction notifications from reaching the other user (excluding replays, but your initial play will not be registered, and you can view it as many times as you like).

Hiding specifically replays isn't a feature I am going to work on - the obvious method I found and tried didn't work and there are plenty of workarounds.
