### ISSUE TITLE
Empty photo / Video When Saving snap from Snap Map

### ISSUE THREAD

**Issue by melbarouzi** [rodit/SnapMod#82]
Hii

Just want to  Address  this bugs , every time  I  tried  to  download  a  snap from  snap map i got  a  empty file saved  ...other snap from friend's are saved  Correctly 
Here a screenshots: 

![Screenshot_20220506-064135_Gallery~01](https://user-images.githubusercontent.com/54691799/167080383-7ef3f3e6-11b0-4550-8d51-2ea95f2d5c5a.jpg)

**Comment by snaphappy1** [comment]
On Android 8.1 with systemless xposed this is happening to me as well. I've tried with Android Download manager enabled and disabled.  Strangely enough on Android 11 with Lsposed it saves them perfectly.

**Comment by rodit** [comment]
I just tried this - these stories are MPD files which can be played with VLC. They are basically just XML which defines a URLs to stream video and audio. I do not plan on fixing this, it would require parsing the MPD and muxing the video and audio.
