### ISSUE TITLE
Saving to gallery 

### ISSUE THREAD

**Issue by Madshuman** [rodit/SnapMod#83]
Does the saving to gallery working? I didn't get any snaps save!

**Comment by Magna-Graecia** [comment]
Yes, it works. Make sure to enable "Allow Saving Snaps" and "Save Any Message" in SnapMod settings. Also make sure to enable "Allow Download Stories" and "Allow Download Public DPs" if it's a story snap or public profile picture that you're trying to save.

You might experience bugs with it depending on the current status of your account (if it's in AB testing or not), so nobody can help you with that. Try saving snaps both from tapping the 3 dots in the upper right-hand corner to get the context menu while viewing a snap, and also by pressing and holding on the snap while in a chat to get the other context menu (make sure "Save Any Message" is enabled for this to work). You might find that at least one of these ways works to save snaps.

**Comment by Madshuman** [comment]
That's work
Thanks alot
