### ISSUE TITLE
Override Add Friend Method is not showing

### ISSUE THREAD

**Issue by Alix8804** [rodit/SnapMod#84]
Please add this future in new APK (Override Add Friend Method)

**Comment by Magna-Graecia** [comment]
I assume it was removed because it wasn't working. Same with "Hide Replay Notifications". Rodit has stated that he will remove features that he can't get working. Another user also reported having been temp banned while trying it, so it probably wouldn't be a good idea to use it anyway.

**Comment by JReverse** [comment]
Wouldn't recommend unless you wanna be spam banned

**Comment by rodit** [comment]
I took this feature out because of temp ban and it wasn't reliable anyway.
